---

- name: Template configuration file
  ansible.builtin.template:
    src: config.j2
    dest: '{{ edgeos_router__temporary_filebase }}-config.txt'
  delegate_to: localhost
  check_mode: false

- name: Push configuration to router
  community.network.edgeos_config:
    src: '{{ edgeos_router__temporary_filebase }}-config.txt'
    save: true
